/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HeadingOutlinerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var import_language = require("@codemirror/language");
var DEFAULT_SETTINGS = {
  headingIndent: true,
  indentSize: 0.5
};
function getHeadingLevel(line) {
  const match = line.match(/^(#{1,6})\s/);
  return match ? match[1].length : 0;
}
function getSectionRangeFromDoc(state, headingLine) {
  const doc = state.doc;
  const level = getHeadingLevel(doc.line(headingLine + 1).text);
  if (level === 0)
    return { startLine: headingLine, endLine: headingLine, level: 0 };
  let endLine = headingLine + 1;
  while (endLine < doc.lines) {
    const l = getHeadingLevel(doc.line(endLine + 1).text);
    if (l > 0 && l <= level)
      break;
    endLine++;
  }
  return { startLine: headingLine, endLine: endLine - 1, level };
}
function findCurrentHeadingLine(state, cursorLine) {
  for (let i = cursorLine; i >= 0; i--) {
    if (getHeadingLevel(state.doc.line(i + 1).text) > 0)
      return i;
  }
  return -1;
}
function findParentHeadingLine(state, fromLine, maxLevel) {
  for (let i = fromLine; i >= 0; i--) {
    const l = getHeadingLevel(state.doc.line(i + 1).text);
    if (l > 0 && l <= maxLevel)
      return i;
  }
  return -1;
}
function findFutureParentHeading(state, headingLine, newLevel) {
  for (let i = headingLine - 1; i >= 0; i--) {
    const l = getHeadingLevel(state.doc.line(i + 1).text);
    if (l > 0 && l < newLevel)
      return i;
  }
  return -1;
}
function findSiblingSection(state, section, direction) {
  const doc = state.doc;
  if (direction === "up") {
    let candidate = section.startLine - 1;
    if (candidate < 0)
      return null;
    const candidateLevel = getHeadingLevel(doc.line(candidate + 1).text);
    if (candidateLevel > 0 && candidateLevel < section.level)
      return null;
    if (candidateLevel > 0 && candidateLevel === section.level) {
      return getSectionRangeFromDoc(state, candidate);
    }
    if (candidateLevel > 0 && candidateLevel > section.level) {
      const parentLine = findParentHeadingLine(state, candidate, section.level);
      if (parentLine >= 0 && getHeadingLevel(doc.line(parentLine + 1).text) === section.level) {
        return getSectionRangeFromDoc(state, parentLine);
      }
      return null;
    }
    for (let i = candidate; i >= 0; i--) {
      const l = getHeadingLevel(doc.line(i + 1).text);
      if (l > 0 && l === section.level) {
        return getSectionRangeFromDoc(state, i);
      }
      if (l > 0 && l < section.level)
        return null;
    }
    return null;
  } else {
    const nextStart = section.endLine + 1;
    if (nextStart >= doc.lines)
      return null;
    for (let i = nextStart; i < doc.lines; i++) {
      const l = getHeadingLevel(doc.line(i + 1).text);
      if (l > 0 && l < section.level)
        return null;
      if (l > 0 && l === section.level) {
        return getSectionRangeFromDoc(state, i);
      }
    }
    return null;
  }
}
function getFoldedRanges(state) {
  const folded = [];
  const iter = (0, import_language.foldedRanges)(state).iter();
  while (iter.value) {
    folded.push({ from: iter.from, to: iter.to });
    iter.next();
  }
  return folded;
}
function getFoldsInSections(state, folds, sections) {
  const result = [];
  for (const fold of folds) {
    const foldLine = state.doc.lineAt(fold.from).number - 1;
    const inSection = sections.some((s) => s.startLine <= foldLine && foldLine <= s.endLine);
    if (inSection) {
      result.push(fold);
    }
  }
  return result;
}
function getFoldAtLine(state, line, folds) {
  const docLine = state.doc.line(line + 1);
  return folds.find((fr) => fr.from >= docLine.from && fr.from <= docLine.to) || null;
}
function filterRootHeadings(headings) {
  if (headings.length <= 1)
    return headings;
  const sorted = [...headings].sort((a, b) => a.line - b.line);
  const roots = [];
  for (const h of sorted) {
    const isContained = roots.some(
      (r) => r.section.startLine <= h.section.startLine && r.section.endLine >= h.section.endLine
    );
    if (!isContained)
      roots.push(h);
  }
  return roots;
}
function collectHeadingsFromSelections(state) {
  const headings = [];
  const seenLines = /* @__PURE__ */ new Set();
  for (const range of state.selection.ranges) {
    const fromLine = state.doc.lineAt(range.from).number - 1;
    const toLine = state.doc.lineAt(range.to).number - 1;
    for (let line = fromLine; line <= toLine; line++) {
      const headingLine = findCurrentHeadingLine(state, line);
      if (headingLine >= 0 && !seenLines.has(headingLine)) {
        seenLines.add(headingLine);
        const level = getHeadingLevel(state.doc.line(headingLine + 1).text);
        headings.push({
          line: headingLine,
          level,
          section: getSectionRangeFromDoc(state, headingLine)
        });
      }
    }
  }
  return headings;
}
function getSelectedVisibleHeadings(state, folds) {
  const headings = [];
  const seenLines = /* @__PURE__ */ new Set();
  for (const range of state.selection.ranges) {
    const fromLine = state.doc.lineAt(range.from).number - 1;
    const toLine = state.doc.lineAt(range.to).number - 1;
    for (let line = fromLine; line <= toLine; line++) {
      const level = getHeadingLevel(state.doc.line(line + 1).text);
      if (level === 0)
        continue;
      if (seenLines.has(line))
        continue;
      const docLine = state.doc.line(line + 1);
      const isHidden = folds.some((f) => f.from < docLine.from && f.to > docLine.from);
      if (isHidden)
        continue;
      seenLines.add(line);
      headings.push({ line, level });
    }
  }
  return headings;
}
function isSingleCursor(state) {
  return state.selection.ranges.every((r) => r.from === r.to);
}
var HeadingOutlinerPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.applyStyle(this.settings.headingIndent, this.settings.indentSize);
    this.registerEditorExtension(
      import_state.Prec.high(import_view.keymap.of([
        {
          key: "Tab",
          run: (cmView) => this.handleTabKey(cmView, 1)
        },
        {
          key: "Shift-Tab",
          run: (cmView) => this.handleTabKey(cmView, -1)
        },
        {
          key: "Ctrl-Shift-ArrowUp",
          run: (cmView) => this.handleMoveKey(cmView, "up")
        },
        {
          key: "Ctrl-Shift-ArrowDown",
          run: (cmView) => this.handleMoveKey(cmView, "down")
        }
      ]))
    );
    this.addSettingTab(new HeadingOutlinerSettingTab(this.app, this));
    this.addCommand({
      id: "fold-more",
      name: "Fold more",
      editorCallback: (editor) => {
        const cmView = editor.cm;
        this.foldMoreSelection(cmView);
      }
    });
    this.addCommand({
      id: "fold-less",
      name: "Fold less",
      editorCallback: (editor) => {
        const cmView = editor.cm;
        this.foldLessSelection(cmView);
      }
    });
  }
  handleTabKey(cmView, delta) {
    const state = cmView.state;
    const cursorPos = state.selection.main.head;
    const cursorLine = state.doc.lineAt(cursorPos).number - 1;
    const currentLineLevel = getHeadingLevel(state.doc.line(cursorLine + 1).text);
    if (currentLineLevel === 0)
      return false;
    this.changeIndentCM6(cmView, delta);
    return true;
  }
  handleMoveKey(cmView, direction) {
    const state = cmView.state;
    const cursorLine = state.doc.lineAt(state.selection.main.head).number - 1;
    const currentLineLevel = getHeadingLevel(state.doc.line(cursorLine + 1).text);
    if (currentLineLevel === 0)
      return false;
    this.moveSectionCM6(cmView, direction);
    return true;
  }
  changeIndentCM6(cmView, delta) {
    const state = cmView.state;
    const allHeadings = collectHeadingsFromSelections(state);
    if (allHeadings.length === 0)
      return;
    const rootHeadings = filterRootHeadings(allHeadings);
    if (rootHeadings.length === 0)
      return;
    const changes = [];
    const doc = state.doc;
    const affectedLines = /* @__PURE__ */ new Set();
    for (const h of rootHeadings) {
      for (let line = h.section.startLine; line <= h.section.endLine; line++) {
        affectedLines.add(line);
      }
    }
    for (const line of Array.from(affectedLines)) {
      const docLine = doc.line(line + 1);
      const level = getHeadingLevel(docLine.text);
      if (level === 0)
        continue;
      const newLevel = level + delta;
      if (newLevel < 1 || newLevel > 6)
        continue;
      const hashCount = level;
      changes.push({
        from: docLine.from,
        to: docLine.from + hashCount,
        insert: "#".repeat(newLevel)
      });
    }
    if (changes.length === 0)
      return;
    const changeSet = import_state.ChangeSet.of(changes, state.doc.length);
    const foldedBefore = getFoldedRanges(state);
    const affectedSections = rootHeadings.map((h) => h.section);
    const foldsToPreserve = getFoldsInSections(state, foldedBefore, affectedSections);
    const parentFoldsToUnfold = [];
    const effects = [];
    if (delta > 0) {
      for (const h of rootHeadings) {
        const newLevel = h.level + delta;
        const parentLine = findFutureParentHeading(state, h.line, newLevel);
        if (parentLine >= 0) {
          const foldRange = getFoldAtLine(state, parentLine, foldedBefore);
          if (foldRange) {
            parentFoldsToUnfold.push(foldRange);
            effects.push(import_language.unfoldEffect.of({
              from: changeSet.mapPos(foldRange.from, 1),
              to: changeSet.mapPos(foldRange.to, -1)
            }));
          }
        }
      }
    }
    const foldsToRestore = foldsToPreserve.filter(
      (f) => !parentFoldsToUnfold.some((pf) => pf.from === f.from && pf.to === f.to)
    );
    cmView.dispatch({
      changes,
      effects: effects.length > 0 ? effects : void 0,
      selection: state.selection.map(changeSet.desc)
    });
    if (foldsToRestore.length > 0) {
      const newState = cmView.state;
      const currentFolds = getFoldedRanges(newState);
      const currentFoldFroms = new Set(currentFolds.map((f) => f.from));
      const restoreEffects = [];
      for (const fold of foldsToRestore) {
        const mappedFrom = changeSet.mapPos(fold.from, 1);
        if (!currentFoldFroms.has(mappedFrom)) {
          const mappedTo = changeSet.mapPos(fold.to, -1);
          restoreEffects.push(import_language.foldEffect.of({ from: mappedFrom, to: mappedTo }));
        }
      }
      if (restoreEffects.length > 0) {
        cmView.dispatch({ effects: restoreEffects });
      }
    }
  }
  moveSectionCM6(cmView, direction) {
    const state = cmView.state;
    const cursorLine = state.doc.lineAt(state.selection.main.head).number - 1;
    const cursorCh = state.selection.main.head - state.doc.line(cursorLine + 1).from;
    const headingLine = findCurrentHeadingLine(state, cursorLine);
    if (headingLine < 0)
      return;
    const section = getSectionRangeFromDoc(state, headingLine);
    const sibling = findSiblingSection(state, section, direction);
    if (!sibling)
      return;
    const doc = state.doc;
    const firstSectionLines = [];
    for (let i = section.startLine; i <= section.endLine; i++) {
      firstSectionLines.push(doc.line(i + 1).text);
    }
    const secondSectionLines = [];
    for (let i = sibling.startLine; i <= sibling.endLine; i++) {
      secondSectionLines.push(doc.line(i + 1).text);
    }
    const newText = direction === "up" ? [...firstSectionLines, ...secondSectionLines].join("\n") : [...secondSectionLines, ...firstSectionLines].join("\n");
    const foldedBefore = getFoldedRanges(state);
    const unfoldEffects = foldedBefore.map((fr) => import_language.unfoldEffect.of(fr));
    const sectionLen = section.endLine - section.startLine + 1;
    const siblingLen = sibling.endLine - sibling.startLine + 1;
    const cursorOffsetInSection = cursorLine - section.startLine;
    let newCursorLine;
    if (direction === "up") {
      newCursorLine = sibling.startLine + cursorOffsetInSection;
    } else {
      newCursorLine = section.startLine + siblingLen + cursorOffsetInSection;
    }
    const linesBeforeCursor = newText.split("\n").slice(0, newCursorLine - Math.min(section.startLine, sibling.startLine));
    const cursorOffset = linesBeforeCursor.reduce((sum, l) => sum + l.length + 1, 0);
    const targetLineText = newText.split("\n")[newCursorLine - Math.min(section.startLine, sibling.startLine)] || "";
    const newCursorCh = Math.min(cursorCh, targetLineText.length);
    const change = {
      from: doc.line(Math.min(section.startLine, sibling.startLine) + 1).from,
      to: doc.line(Math.max(section.endLine, sibling.endLine) + 1).to,
      insert: newText
    };
    cmView.dispatch({
      changes: change,
      effects: unfoldEffects,
      selection: import_state.EditorSelection.cursor(doc.line(Math.min(section.startLine, sibling.startLine) + 1).from + cursorOffset + newCursorCh)
    });
    const newState = cmView.state;
    const newFoldEffects = [];
    for (const fr of foldedBefore) {
      const oldLine = doc.lineAt(fr.from).number - 1;
      let newLine;
      if (direction === "up") {
        if (oldLine >= section.startLine && oldLine <= section.endLine) {
          newLine = oldLine - siblingLen;
        } else if (oldLine >= sibling.startLine && oldLine <= sibling.endLine) {
          newLine = oldLine + sectionLen;
        } else {
          newLine = oldLine;
        }
      } else {
        if (oldLine >= section.startLine && oldLine <= section.endLine) {
          newLine = oldLine + siblingLen;
        } else if (oldLine >= sibling.startLine && oldLine <= sibling.endLine) {
          newLine = oldLine - sectionLen;
        } else {
          newLine = oldLine;
        }
      }
      if (newLine >= 0 && newLine < newState.doc.lines) {
        const newDocLine = newState.doc.line(newLine + 1);
        const foldRange = (0, import_language.foldable)(newState, newDocLine.from, newDocLine.to);
        if (foldRange) {
          newFoldEffects.push(import_language.foldEffect.of(foldRange));
        }
      }
    }
    if (newFoldEffects.length > 0) {
      cmView.dispatch({ effects: newFoldEffects });
    }
  }
  foldLessSelection(cmView) {
    const state = cmView.state;
    const folds = getFoldedRanges(state);
    let targetHeadings;
    if (isSingleCursor(state)) {
      const cursorLine = state.doc.lineAt(state.selection.main.head).number - 1;
      const headingLine = findCurrentHeadingLine(state, cursorLine);
      if (headingLine < 0)
        return;
      targetHeadings = [{ line: headingLine, level: getHeadingLevel(state.doc.line(headingLine + 1).text) }];
    } else {
      targetHeadings = getSelectedVisibleHeadings(state, folds);
    }
    if (targetHeadings.length === 0)
      return;
    const foldedHeadings = targetHeadings.filter((h) => {
      const docLine = state.doc.line(h.line + 1);
      return folds.some((f) => f.from >= docLine.from && f.from <= docLine.to);
    });
    if (foldedHeadings.length === 0)
      return;
    const minLevel = Math.min(...foldedHeadings.map((h) => h.level));
    const effects = [];
    for (const h of foldedHeadings) {
      if (h.level !== minLevel)
        continue;
      const docLine = state.doc.line(h.line + 1);
      const fold = folds.find((f) => f.from >= docLine.from && f.from <= docLine.to);
      if (fold) {
        effects.push(import_language.unfoldEffect.of(fold));
      }
    }
    if (effects.length > 0) {
      cmView.dispatch({ effects });
    }
  }
  foldMoreSelection(cmView) {
    const state = cmView.state;
    const folds = getFoldedRanges(state);
    let targetHeadings;
    if (isSingleCursor(state)) {
      const cursorLine = state.doc.lineAt(state.selection.main.head).number - 1;
      const headingLine = findCurrentHeadingLine(state, cursorLine);
      if (headingLine < 0)
        return;
      targetHeadings = [{ line: headingLine, level: getHeadingLevel(state.doc.line(headingLine + 1).text) }];
    } else {
      targetHeadings = getSelectedVisibleHeadings(state, folds);
    }
    if (targetHeadings.length === 0)
      return;
    const unfoldedHeadings = targetHeadings.filter((h) => {
      const docLine = state.doc.line(h.line + 1);
      return !folds.some((f) => f.from >= docLine.from && f.from <= docLine.to);
    });
    if (unfoldedHeadings.length === 0)
      return;
    const maxLevel = Math.max(...unfoldedHeadings.map((h) => h.level));
    const effects = [];
    for (const h of unfoldedHeadings) {
      if (h.level !== maxLevel)
        continue;
      const docLine = state.doc.line(h.line + 1);
      const foldRange = (0, import_language.foldable)(state, docLine.from, docLine.to);
      if (foldRange) {
        effects.push(import_language.foldEffect.of(foldRange));
      }
    }
    if (effects.length > 0) {
      cmView.dispatch({ effects });
    }
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  applyStyle(enabled, size) {
    activeDocument.body.classList.toggle("heading-outliner-indent", enabled);
    if (enabled) {
      activeDocument.body.style.setProperty("--heading-indent-size", `${size}em`);
    } else {
      activeDocument.body.style.removeProperty("--heading-indent-size");
    }
  }
  onunload() {
    this.applyStyle(false, 0);
  }
};
var HeadingOutlinerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Indent headings by level").setDesc("Visually indent headings in the editor based on their level.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.headingIndent).onChange(async (value) => {
        this.plugin.settings.headingIndent = value;
        this.plugin.applyStyle(value, this.plugin.settings.indentSize);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Indent size (em)").setDesc("How much each heading level is indented relative to the previous level.").addSlider(
      (slider) => slider.setLimits(0.1, 2, 0.1).setValue(this.plugin.settings.indentSize).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.indentSize = value;
        this.plugin.applyStyle(this.plugin.settings.headingIndent, value);
        await this.plugin.saveSettings();
      })
    );
  }
};

/* nosourcemap */